import { Serie } from './serie.js';
export const series = [
    new Serie(1, "Breaking Bad", "AMC", 5, "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer.", "https://www.amc.com/shows/breaking-bad", "https://images4.alphacoders.com/675/thumb-1920-675471.jpg"),
    new Serie(2, "Orange Is the New Black", "Netflix", 6, "The series begins revolving around Piper Chapman, a woman in her thirties living in New York City who is sentenced to 15 months in Litchfield Penitentiary.", "https://www.netflix.com/co/title/70242311", "https://m.media-amazon.com/images/M/MV5BMjA3MTE5ODM3M15BMl5BanBnXkFtZTgwNTIyMjQ5NTM@._V1_.jpg"),
    new Serie(3, "Game of Thrones", "HBO", 7, "American fantasy drama.", "https://www.hbo.com/game-of-thrones", "https://images.ctfassets.net/fy5ib9j6vdru/6KXluR6i32QuY5XFiBgKV5/16699e65650ce0148d0f7ac8452457bc/got_max_logo_800x450.jpg"),
    new Serie(4, "The Big Bang Theory", "CBS", 12, "Leonard and Sheldon are brilliant physicists—geniuses in the laboratory but socially challenged everywhere else. Enter beautiful, street-smart neighbor Penny, who aims to teach them a thing or two about life.", "https://www.cbs.com/shows/big_bang_theory/about/", "https://th.bing.com/th/id/R.f1ecfa4cfc0fa5912d77ffe9c6e5a439?rik=LOwo%2byMpxy%2fe8A&pid=ImgRaw&r=0"),
    new Serie(5, "Sherlock", "BBC", 4, "Sherlock depicts consulting detective Sherlock Holmes solving various mysteries in modern-day London.", "https://www.bbc.co.uk/programmes/b018ttws", "https://th.bing.com/th/id/OIP.H3I459JW66yo2lqdlF_oiwHaEo?rs=1&pid=ImgDetMain"),
    new Serie(6, "A Very English Scandal", "BBC", 2, "A Very English Scandal is a fact-based three-part British television comedy-drama miniseries.", "https://www.bbc.co.uk/programmes/p065smy4", "https://th.bing.com/th/id/R.4fc5e222ed30e7da4b93c7c1d97b4c21?rik=4rQJywW1qX2%2bIQ&pid=ImgRaw&r=0")
];
